language: rust

env:
  global:
    - RUST_MIN_STACK=81920000
  jobs:
    - CC=gcc
    - CC=clang


os:
 - linux
 - osx

osx_image: xcode11.2
dist: bionic

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test --all
