[package]
name = "pqcrypto"
description = "Post-Quantum cryptographic primitives"
readme = "README.md"
version = "0.11.1"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rustpq/"
repository = "https://github.com/rustpq/pqcrypto/"
keywords = ["cryptography", "post-quantum", "security"]
categories = ["cryptography"]

[dependencies]
pqcrypto-traits = { path = "../pqcrypto-traits", version = "0.3.2" }
pqcrypto-kyber = { path = "../pqcrypto-kyber", version = "0.6.5", optional = true }
pqcrypto-frodo = { path = "../pqcrypto-frodo", version = "0.4.3", optional = true }
pqcrypto-ntru = { path = "../pqcrypto-ntru", version = "0.4.2", optional = true }
pqcrypto-saber = { path = "../pqcrypto-saber", version = "0.1.3", optional = true }
pqcrypto-ledacryptkem = { path = "../pqcrypto-ledacryptkem", version = "0.0.4", optional = true }
pqcrypto-threebears = { path = "../pqcrypto-threebears", version = "0.2.0", optional = true }
pqcrypto-classicmceliece = { path = "../pqcrypto-classicmceliece", version = "0.1.0", optional = true }
pqcrypto-newhope = { path = "../pqcrypto-newhope", version = "0.1.2", optional = true }
pqcrypto-hqc = { path = "../pqcrypto-hqc", version = "0.0.1", optional = true }
pqcrypto-mqdss = { path = "../pqcrypto-mqdss", version = "0.3.0", optional = true }
pqcrypto-dilithium = { path = "../pqcrypto-dilithium", version = "0.3.1", optional = true }
pqcrypto-falcon = { path = "../pqcrypto-falcon", version = "0.2.2", optional = true }
pqcrypto-qtesla = { path = "../pqcrypto-qtesla", version = "0.1.1", optional = true }
pqcrypto-rainbow = { path = "../pqcrypto-rainbow", version = "0.1.2", optional = true }
pqcrypto-sphincsplus = { path = "../pqcrypto-sphincsplus", version = "0.5.0", optional = true }

[features]
default = ["pqcrypto-kyber","pqcrypto-frodo","pqcrypto-ntru","pqcrypto-saber","pqcrypto-threebears","pqcrypto-classicmceliece","pqcrypto-newhope","pqcrypto-hqc","pqcrypto-mqdss","pqcrypto-dilithium","pqcrypto-falcon","pqcrypto-qtesla","pqcrypto-rainbow","pqcrypto-sphincsplus",]
cryptographically-insecure = ["pqcrypto-ledacryptkem/cryptographically-insecure",]

[badges]
travis-ci = { repository = "rustpq/pqcrypto", branch = "master" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true