[package]
name = "pqcrypto"
description = "Post-Quantum cryptographic primitives"
readme = "README.md"
version = "0.6.1"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rustpq/"
repository = "https://github.com/rustpq/pqcrypto/"
keywords = ["cryptography", "post-quantum", "security"]
categories = ["cryptography"]

[dependencies]
pqcrypto-traits = { path = "../pqcrypto-traits", version = "0.3.0" }
pqcrypto-kyber = { path = "../pqcrypto-kyber", version = "0.4.1" }
pqcrypto-frodo = { path = "../pqcrypto-frodo", version = "0.4.1" }
pqcrypto-ntru = { path = "../pqcrypto-ntru", version = "0.4.1" }
pqcrypto-saber = { path = "../pqcrypto-saber", version = "0.1.1" }
pqcrypto-mqdss = { path = "../pqcrypto-mqdss", version = "0.2.2" }
pqcrypto-dilithium = { path = "../pqcrypto-dilithium", version = "0.1.1" }
pqcrypto-falcon = { path = "../pqcrypto-falcon", version = "0.1.0" }
pqcrypto-sphincsplus = { path = "../pqcrypto-sphincsplus", version = "0.4.2" }

[badges]
travis-ci = { repository = "rustpq/pqcrypto", branch = "master" }
maintenance = { status = "actively-developed" }