[package]
name = "pqcrypto-internals"
description = "Provides safe API functions to the PQCRYPTO traits"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
license = "CC0"

[dependencies]
rand = "0.5.0"
libc = "0.1.0"

[lib]
crate-type=["staticlib", "cdylib"]
