[package]
name = "pqcrypto-internals"
description = "Provides safe API functions to the PQCRYPTO traits"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
repository = "https://github.com/rustpq/pqcrypto/"
license = "CC0-1.0"

[dependencies]
rand = "0.6.0"
libc = "0.2.0"

[lib]
crate-type=["staticlib", "cdylib"]
